# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hotelmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form1(object):
    def setupUi(self, Form1):
        Form1.setObjectName("Form1")
        Form1.resize(843, 1042)
        Form1.setStyleSheet("QWidget #Form1 {background-color:rgb(255,255,255);}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(Form1)
        self.frame.setMinimumSize(QtCore.QSize(700, 0))
        self.frame.setStyleSheet("\n"
"\n"
"background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.l1 = QtWidgets.QLabel(self.frame)
        self.l1.setGeometry(QtCore.QRect(90, 20, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setStyleSheet("border: 3px solid #aaff00;\n"
"color: rgb(170, 0, 255);\n"
"border-radius: 10px;\n"
"")
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(self.frame)
        self.l2.setGeometry(QtCore.QRect(260, 90, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.l2.setAlignment(QtCore.Qt.AlignCenter)
        self.l2.setObjectName("l2")
        self.l4 = QtWidgets.QLabel(self.frame)
        self.l4.setGeometry(QtCore.QRect(440, 180, 191, 151))
        self.l4.setMinimumSize(QtCore.QSize(0, 0))
        self.l4.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"border: 3px solid blue;\n"
"border-radius: 10px;")
        self.l4.setText("")
        self.l4.setPixmap(QtGui.QPixmap("C:/Users/Kathick/Desktop/pizza.jpg"))
        self.l4.setScaledContents(True)
        self.l4.setObjectName("l4")
        self.l3 = QtWidgets.QLabel(self.frame)
        self.l3.setGeometry(QtCore.QRect(60, 140, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(18)
        self.l3.setFont(font)
        self.l3.setStyleSheet("border: 3px solid blue;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.l3.setAlignment(QtCore.Qt.AlignCenter)
        self.l3.setObjectName("l3")
        self.c3 = QtWidgets.QCheckBox(self.frame)
        self.c3.setGeometry(QtCore.QRect(40, 290, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(15)
        self.c3.setFont(font)
        self.c3.setStyleSheet("color: rgb(255, 255, 255);")
        self.c3.setObjectName("c3")
        self.l7 = QtWidgets.QLabel(self.frame)
        self.l7.setGeometry(QtCore.QRect(310, 290, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.l7.setFont(font)
        self.l7.setStyleSheet("color: rgb(255, 255, 255);")
        self.l7.setObjectName("l7")
        self.c2 = QtWidgets.QCheckBox(self.frame)
        self.c2.setGeometry(QtCore.QRect(40, 240, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(15)
        self.c2.setFont(font)
        self.c2.setStyleSheet("color: rgb(255, 255, 255);")
        self.c2.setObjectName("c2")
        self.c1 = QtWidgets.QCheckBox(self.frame)
        self.c1.setGeometry(QtCore.QRect(40, 190, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(15)
        self.c1.setFont(font)
        self.c1.setStyleSheet("color: rgb(255, 255, 255);")
        self.c1.setObjectName("c1")
        self.l6 = QtWidgets.QLabel(self.frame)
        self.l6.setGeometry(QtCore.QRect(310, 240, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.l6.setFont(font)
        self.l6.setStyleSheet("color: rgb(255, 255, 255);")
        self.l6.setObjectName("l6")
        self.l5 = QtWidgets.QLabel(self.frame)
        self.l5.setGeometry(QtCore.QRect(310, 190, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.l5.setFont(font)
        self.l5.setStyleSheet("color: rgb(255, 255, 255);")
        self.l5.setObjectName("l5")
        self.l9 = QtWidgets.QLabel(self.frame)
        self.l9.setGeometry(QtCore.QRect(40, 430, 191, 151))
        self.l9.setStyleSheet("border: 3px solid red;\n"
"border-radius: 10px;")
        self.l9.setText("")
        self.l9.setPixmap(QtGui.QPixmap("C:/Users/Kathick/Desktop/burger.jpg"))
        self.l9.setScaledContents(True)
        self.l9.setObjectName("l9")
        self.l8 = QtWidgets.QLabel(self.frame)
        self.l8.setGeometry(QtCore.QRect(440, 380, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(18)
        self.l8.setFont(font)
        self.l8.setStyleSheet("border: 3px solid red;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.l8.setAlignment(QtCore.Qt.AlignCenter)
        self.l8.setObjectName("l8")
        self.c4 = QtWidgets.QCheckBox(self.frame)
        self.c4.setGeometry(QtCore.QRect(290, 440, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(15)
        self.c4.setFont(font)
        self.c4.setStyleSheet("color: rgb(255, 255, 255);")
        self.c4.setObjectName("c4")
        self.c5 = QtWidgets.QCheckBox(self.frame)
        self.c5.setGeometry(QtCore.QRect(290, 490, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(15)
        self.c5.setFont(font)
        self.c5.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.c5.setObjectName("c5")
        self.c6 = QtWidgets.QCheckBox(self.frame)
        self.c6.setGeometry(QtCore.QRect(290, 540, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(15)
        self.c6.setFont(font)
        self.c6.setStyleSheet("color: rgb(255, 255, 255);")
        self.c6.setObjectName("c6")
        self.l10 = QtWidgets.QLabel(self.frame)
        self.l10.setGeometry(QtCore.QRect(580, 440, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.l10.setFont(font)
        self.l10.setStyleSheet("color: rgb(255, 255, 255);")
        self.l10.setObjectName("l10")
        self.l11 = QtWidgets.QLabel(self.frame)
        self.l11.setGeometry(QtCore.QRect(580, 490, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.l11.setFont(font)
        self.l11.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.l11.setObjectName("l11")
        self.l12 = QtWidgets.QLabel(self.frame)
        self.l12.setGeometry(QtCore.QRect(580, 540, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.l12.setFont(font)
        self.l12.setStyleSheet("color: rgb(255, 255, 255);")
        self.l12.setObjectName("l12")
        self.l13 = QtWidgets.QLabel(self.frame)
        self.l13.setGeometry(QtCore.QRect(190, 620, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.l13.setFont(font)
        self.l13.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 3px solid white;\n"
"border-radius: 10px;")
        self.l13.setAlignment(QtCore.Qt.AlignCenter)
        self.l13.setObjectName("l13")
        self.horizontalLayout.addWidget(self.frame)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(Form1)
        QtCore.QMetaObject.connectSlotsByName(Form1)
        self.c1.stateChanged.connect(self.fn1)
        self.c2.stateChanged.connect(self.fn1)
        self.c3.stateChanged.connect(self.fn1)
        self.c4.stateChanged.connect(self.fn1)
        self.c5.stateChanged.connect(self.fn1)
        self.c6.stateChanged.connect(self.fn1)
        
    def fn1(self):
        s=0
        if self.c1.isChecked()==True:
                s=s+160
        if self.c2.isChecked()==True:
                s=s+180
        if self.c3.isChecked()==True:
                s=s+250
        if self.c4.isChecked()==True:
                s=s+80
        if self.c5.isChecked()==True:
                s=s+110
        if self.c6.isChecked()==True:
                s=s+155
        self.l13.setText('Amount: Rs.' + str(s))






    def retranslateUi(self, Form1):
        _translate = QtCore.QCoreApplication.translate
        Form1.setWindowTitle(_translate("Form1", "Menu Card"))
        self.l1.setText(_translate("Form1", "V.R Restaurant"))
        self.l2.setText(_translate("Form1", "MENU"))
        self.l3.setText(_translate("Form1", "PIZZA"))
        self.c3.setText(_translate("Form1", "PANEER TIKKA (REG)"))
        self.l7.setText(_translate("Form1", "Rs.250"))
        self.c2.setText(_translate("Form1", "DOUBLE CHEESE (REG)"))
        self.c1.setText(_translate("Form1", "MARGHERITA (REG)"))
        self.l6.setText(_translate("Form1", "Rs.180"))
        self.l5.setText(_translate("Form1", "Rs.160"))
        self.l8.setText(_translate("Form1", "BURGER"))
        self.c4.setText(_translate("Form1", "MEXICAN BURGER (VEG)"))
        self.c5.setText(_translate("Form1", "CHICKEN BURGER "))
        self.c6.setText(_translate("Form1", "LAMB BURGER"))
        self.l10.setText(_translate("Form1", "Rs.80"))
        self.l11.setText(_translate("Form1", "Rs.110"))
        self.l12.setText(_translate("Form1", "Rs.155"))
        self.l13.setText(_translate("Form1", "Amount: Rs.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form1 = QtWidgets.QWidget()
    ui = Ui_Form1()
    ui.setupUi(Form1)
    Form1.showMaximized()
    sys.exit(app.exec_())
